### ISSUE TITLE
How much should Adapters do?

### ISSUE THREAD

**Issue by CWSpear** [cohesivelabs/goferfs#2]
How much should the adapters do, and how much should we abstract away into the top level?

For example, I currently have it ensuring that the directory exists. This may not really be necessary for all Adapters, or may cause things to be slower than needed.

It also does some other checks and cleans up paths.

Where do we draw the line?

**Comment by jmartin84** [comment]
I think we need to map out everything its doing right now and then go from there.

Aside from that do we really need to expose a method to see if I directory exists? It wouldn't really be applicable to most apis and local file write operations would create the directory anyway. Thoughts?

**Comment by CWSpear** [comment]
There isn't a separate method. There is just `has` (could be renamed `exists`?) for both files and directories.

**Comment by jmartin84** [comment]
I'm just not sure if its super applicable outside of the local FS.

**Comment by CWSpear** [comment]
Why not? S3 has the concept of directories and Dropbox maps to a regular filesystem, so it definitely has directories.

I mean, I can't think of a particular use-case for needing to know if a directory exists off the top of my head, but I don't see how the underlying filesystem makes a difference either way, which is what we're discussing, right?

**Comment by jmartin84** [comment]
I'm actually thinking in terms of when the file system is abstracted away behind a rest api. I can't think of a service that does this off the top of my head - but in a system like that there may not be a concept of a true directory structure. I admit that this is probably falling into edge case territory though.

**Comment by CWSpear** [comment]
Well, S3 lets you delete a directory...

**Comment by CWSpear** [comment]
We got a little off track, but this still needs to be addressed. What all can/should the top level handle? What should be left off to the adapter?
