### ISSUE TITLE
Directories

### ISSUE THREAD

**Issue by CWSpear** [cohesivelabs/goferfs#6]
Can you can and rename directories recursively?

Can you save multiple files in a directory tree structure?

i.e.:

```js
filesystem.writeDir({
  path: contents,
  dir: {
    path: contents2,
  }
});

// same as
Promise.all([
  filesystem.write('path', contents),
  filesystem.write('dir/path', contents2),
]);
```

**Comment by jmartin84** [comment]
not sure I see the use case around renaming directories recursively, can you explain what that would look like?

**Comment by CWSpear** [comment]
I just meant renaming directories. so rename `some/dir` to `some/other/dir` so `some/dir/banana.png` would now be `some/other/dir/banana.png` etc.

**Comment by jmartin84** [comment]
oh, then yes

**Comment by CWSpear** [comment]
What about the second item? `writeDir`?

**Comment by CWSpear** [comment]
I do think I like that method (maybe not that name), but more of a v2 thing.

**Comment by CWSpear** [comment]
(It's something the top level could support, you wouldn't even need to support it directly on the adapter level. It just rewrites the call to the form in my example.)
